name: local_common
description: Local common
version: 0.5.0
publish_to: 'none'

environment:
  sdk: ^3.1.0

dependencies:
  drift: ^2.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.0.20
  sqflite_common_ffi: ^2.2.5
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  build_runner : ^2.3.3
  chopper_generator: ^7.0.0
  custom_lint: ^0.5.3
  drift_dev: ^2.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
  generate: true

targets:
