name: sma_common_ux
description: SMA Common UX
publish_to: 'none'
version: 0.5.0
repository: https://github.com/agarwalabhii/ics-sma-v2/tree/master/sma_common_ux

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.1.0"
  
dependencies:
  args: ^2.0.0
  chopper: ^7.0.5
  clock: ^1.1.0
  connectivity_plus: ^4.0.1
  date_field: ^3.0.0
  dropdown_textfield: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  flutter_riverpod: ^2.3.6
  freezed: ^2.4.1
  hooks_riverpod: ^2.4.1
  http: ^1.1.0
  intl: ^0.18.0
  jose: ^0.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  logging: ^1.0.0
  markdown: ^7.1.1
  multi_select_flutter: ^4.1.3 
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  pluto_grid: ^7.0.2
  pointycastle: ^3.0.0
  provider: ^6.0.5
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.0.20
  sma_local_data:
    git:
      url: https://github.com/agarwalabhii/ics-sma-v2/tree/master/sma_local_data
      ref: master
  sma_remote_data:
    git:
      url: https://github.com/agarwalabhii/ics-sma-v2/tree/master/sma_remote_data
      ref: master
  syncfusion_flutter_calendar: ^23.1.36
  tuple: ^2.0.2
  url_launcher: ^6.1.7
  webview_universal: ^0.0.4
  xxtea: ^2.1.0

dev_dependencies:
  build_runner : ^2.3.3
  chopper_generator: ^7.0.2
  custom_lint: ^0.5.3
  drift_dev: ^2.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.2.0
  msix: ^3.13.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.3

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
    sma_local_data:
        path: ../sma_local_data/
    sma_remote_data:
        path: ../sma_remote_data/
