name: anet
description: Anet

publish_to: 'none'
version: 1.0.1-0000
# Version 
# + means it is a regular release build,
# while - would indicate a pre-release build.
# (No build number after x.y.z also indicates a release build like +)


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.1.0"
  
dependencies:
  args: ^2.0.0
  chopper: ^7.0.5
  clock: ^1.1.0
  date_field: ^3.0.0
  drift: ^2.12.1
  dropdown_textfield: ^1.0.8
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.4.1
  hooks_riverpod: ^2.4.1
  http: ^1.1.0
  intl: ^0.18.0
  jose: ^0.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  logger: ^2.0.2+1
  meta: ^1.0.0
  multi_select_flutter: ^4.1.3 
  open_app_file: ^4.0.2
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  pluto_grid: ^7.0.2
  pointycastle: ^3.0.0
  provider: ^6.0.5
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.0.20
  sma_common_ux:
    path: ../sma_common_ux/
  sma_local_data:
    path: ../sma_local_data/
  sma_remote_data:
    path: ../sma_remote_data/
  syncfusion_flutter_calendar: ^23.1.36
  syncfusion_flutter_pdf: ^23.1.44
  syncfusion_flutter_pdfviewer: ^23.1.44
  tuple: ^2.0.2
  url_launcher: ^6.1.7
  webview_universal: ^0.0.4
  xxtea: ^2.1.0

dev_dependencies:
  build_runner : ^2.3.3
  chopper_generator: ^7.0.2
  custom_lint: ^0.5.3
  drift_dev: ^2.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.2.0
  msix: ^3.13.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.3
 
msix_config:
  app_installer :
    publish_folder_path: publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  capabilities: internetClient, location, microphone, webcam
  certificate_path : "AnetCodeSigning.pfx"
  certificate_password : F5|5PH|5C3rt!
  display_name: AssuranceNET ICS
  identity_name: gov.fsis.assurancenet.ics
  install_certificate: true
  #msix: ^3.13.2
  msix_version: 1.0.1.0000
  publisher_display_name: USDA - FSIS
  #sign_msix: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/certs/
    - assets/database/
    - assets/govform/
    - assets/icons/
    - assets/images/
    - assets/release_notes/
