import 'package:domain_database/src/dep/repository/model_base.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:local_common/database.dart';

abstract class FirmGeneralInfoModel extends ModelBase {
  String? get name;
  void setName(WidgetRef ref, String? newValue);
  String? get doingBusinessAs;
  void setDoingBusinessAs(WidgetRef ref, String? newValue);
  String? get alsoKnownAs;
  void setAlsoKnownAs(WidgetRef ref, String? newValue);
  String? get previousName;
  void setPreviousName(WidgetRef ref, String? newValue);
  bool? get contactRegionalOffice;
  void setContactRegionalOffice(WidgetRef ref, bool? newValue);
  bool? get mailingAddressSameAsFirmAddress;
  void setMailingAddressSameAsFirmAddress(WidgetRef ref, bool? newValue);
  String? get establishmentNumber;
  void setEstablishmentNumber(WidgetRef ref, String? newValue);
  String? get risk;
  void setRisk(WidgetRef ref, String? newValue);
  String? get regionCode;
  void setRegionCode(WidgetRef ref, String? newValue);
  String? get subRegionCode;
  void setSubRegionCode(WidgetRef ref, String? newValue);
  String? get assignCode;
  void setAssignCode(WidgetRef ref, String? newValue);
  String? get numberOfFloors;
  void setNumberOfFloors(WidgetRef ref, String? newValue);
  SingleString? get numberOfEmp;
  void setNumberOfEmp(WidgetRef ref, SingleString? newValue);
  String? get approxSqFootage;
  void setApproxSqFootage(WidgetRef ref, String? newValue);
  SingleString? get primaryBusinessType;
  void setPrimaryBusinessType(WidgetRef ref, SingleString? newValue);
  SingleString? get secondaryBusinessType;
  void setSecondaryBusinessType(WidgetRef ref, SingleString? newValue);
  SingleString? get tertiaryBusinessType;
  void setTertiaryBusinessType(WidgetRef ref, SingleString? newValue);
  MultiString? get businessActivities;
  void setBusinessActivities(WidgetRef ref, MultiString? newValue);
  String? get tier;
  void setTier(WidgetRef ref, String? newValue);
  bool? get isFirmRegistered;
  void setIsFirmRegistered(WidgetRef ref, bool? newValue);
  String? get comments;
  void setComments(WidgetRef ref, String? newValue);
  bool? get firmIsUnderOrder;
  void setFirmIsUnderOrder(WidgetRef ref, bool? newValue);
  MultiString? get typeOfOrder;
  void setTypeOfOrder(WidgetRef ref, MultiString? newValue);
  bool? get orderIsPermanent;
  void setOrderIsPermanent(WidgetRef ref, bool? newValue);
  DateTime? get expirationOfOrder;
  void setExpirationOfOrder(WidgetRef ref, DateTime? newValue);
  String? get backupEnergySource;
  void setBackupEnergySource(WidgetRef ref, String? newValue);
  bool? get applyToAll;
  void setApplyToAll(WidgetRef ref, bool? newValue);
  bool? get sundayClosed;
  void setSundayClosed(WidgetRef ref, bool? newValue);
  String? get sundayOpen;
  void setSundayOpen(WidgetRef ref, String? newValue);
  String? get sundayClose;
  void setSundayClose(WidgetRef ref, String? newValue);
  bool? get mondayClosed;
  void setMondayClosed(WidgetRef ref, bool? newValue);
  String? get mondayOpen;
  void setMondayOpen(WidgetRef ref, String? newValue);
  String? get mondayClose;
  void setMondayClose(WidgetRef ref, String? newValue);
  bool? get tuesdayClosed;
  void setTuesdayClosed(WidgetRef ref, bool? newValue);
  String? get tuesdayOpen;
  void setTuesdayOpen(WidgetRef ref, String? newValue);
  String? get tuesdayClose;
  void setTuesdayClose(WidgetRef ref, String? newValue);
  bool? get wednesdayClosed;
  void setWednesdayClosed(WidgetRef ref, bool? newValue);
  String? get wednesdayOpen;
  void setWednesdayOpen(WidgetRef ref, String? newValue);
  String? get wednesdayClose;
  void setWednesdayClose(WidgetRef ref, String? newValue);
  bool? get thursdayClosed;
  void setThursdayClosed(WidgetRef ref, bool? newValue);
  String? get thursdayOpen;
  void setThursdayOpen(WidgetRef ref, String? newValue);
  String? get thursdayClose;
  void setThursdayClose(WidgetRef ref, String? newValue);
  bool? get fridayClosed;
  void setFridayClosed(WidgetRef ref, bool? newValue);
  String? get fridayOpen;
  void setFridayOpen(WidgetRef ref, String? newValue);
  String? get fridayClose;
  void setFridayClose(WidgetRef ref, String? newValue);
  bool? get saturdayClosed;
  void setSaturdayClosed(WidgetRef ref, bool? newValue);
  String? get saturdayOpen;
  void setSaturdayOpen(WidgetRef ref, String? newValue);
  String? get saturdayClose;
  void setSaturdayClose(WidgetRef ref, String? newValue);
}
