import 'package:sma_local_data/sma_local_data.dart';
import 'package:sma_remote_data/src/anet_apis/anet_schema.models.swagger.dart';
import 'package:sma_remote_data/src/anet_apis/value_placeholder.dart';
import 'package:sma_remote_data/src/domain/choice_bool.dart';

extension FirmGeneralInfoRemote on FirmInfo {
  FirmGeneralInfoData toFirmGenerallInfo({int? localId}) {
    return FirmGeneralInfoData(
      id: firmId!,
      recordType: RecordType.remote,
      name: name,
      doingBusinessAs: doingBusAs,
      alsoKnownAs: alsoKnownAs,
      previousName: prevName,
      establishmentNumber: estNum,
      risk: risk,
      regionCode: regionCode,
      subRegionCode: subRegionCode,
      numberOfFloors: numFloors,
      numberOfEmp: apxNumEmployees,
      approxSqFootage: apxSqFoot,
      primaryBusinessType: primaryBusType,
      secondaryBusinessType: secondaryBusType,
      tertiaryBusinessType: tertiaryBusType,
      businessActivities: MultiString.fromString(businessActivities),
      isFirmRegistered: (firmRegistrationInfo != null),
      backupEnergySource: isEnergySource,
      firmIsUnderOrder: localMappedValueTBD(),
      typeOfOrder: localMappedValueTBD(),
      orderIsPermanent: ChoiceValue.fromRemoteModel(isOrderPermanent).value,
      expirationOfOrder: exprOrderDate,
      isSundayClosed: ChoiceValue.fromRemoteModel(isSunClosed).value,
      sundayOpenTime: sunOpenTime,
      sundayCloseTime: sunCloseTime,
      isMondayClosed: ChoiceValue.fromRemoteModel(isMonClosed).value,
      mondayOpenTime: monOpenTime,
      mondayCloseTime: monCloseTime,
      isTuesdayClosed: ChoiceValue.fromRemoteModel(isTueClosed).value,
      tuesdayOpenTime: tueOpenTime,
      tuesdayCloseTime: tueCloseTime,
      isWednesdayClosed: ChoiceValue.fromRemoteModel(isWedClosed).value,
      wednesdayOpenTime: wedOpenTime,
      wednesdayCloseTime: wedCloseTime,
      isThursdayClosed: ChoiceValue.fromRemoteModel(isThuClosed).value,
      thursdayOpenTime: thuOpenTime,
      thursdayCloseTime: thuCloseTime,
      isFridayClosed: ChoiceValue.fromRemoteModel(isFriClosed).value,
      fridayOpenTime: friOpenTime,
      fridayCloseTime: friCloseTime,
      isSaturdayClosed: ChoiceValue.fromRemoteModel(isSatClosed).value,
      saturdayOpenTime: satOpenTime,
      saturdayCloseTime: satCloseTime,
    );
  }

  FirmInfo copyWithFirmGeneralInfo(FirmGeneralInfoData local) {
    return copyWith(
      name: local.name,
      doingBusAs: local.doingBusinessAs,
      alsoKnownAs: local.alsoKnownAs,
      prevName: local.previousName,
      estNum: local.establishmentNumber,
      risk: local.risk,
      regionCode: local.regionCode,
      subRegionCode: local.subRegionCode,
      numFloors: local.numberOfFloors,
      apxNumEmployees: local.numberOfEmp,
      primaryBusType: local.primaryBusinessType,
      secondaryBusType: local.secondaryBusinessType,
      tertiaryBusType: local.tertiaryBusinessType,
      businessActivities: local.businessActivities?.oneString,
      isEnergySource: local.backupEnergySource,
      isOrderPermanent: ChoiceBool(local.orderIsPermanent).asYNNull,
      exprOrderDate: local.expirationOfOrder,
      isSunClosed: ChoiceBool(local.isSundayClosed).asYNNull,
      sunOpenTime: local.sundayOpenTime,
      sunCloseTime: local.sundayCloseTime,
      isMonClosed: ChoiceBool(local.isMondayClosed).asYNNull,
      monOpenTime: local.mondayOpenTime,
      monCloseTime: local.mondayCloseTime,
      isTueClosed: ChoiceBool(local.isTuesdayClosed).asYNNull,
      tueOpenTime: local.tuesdayOpenTime,
      tueCloseTime: local.tuesdayCloseTime,
      isWedClosed: ChoiceBool(local.isWednesdayClosed).asYNNull,
      wedOpenTime: local.wednesdayOpenTime,
      wedCloseTime: local.wednesdayCloseTime,
      isThuClosed: ChoiceBool(local.isThursdayClosed).asYNNull,
      thuOpenTime: local.thursdayOpenTime,
      thuCloseTime: local.thursdayCloseTime,
      isFriClosed: ChoiceBool(local.isFridayClosed).asYNNull,
      friOpenTime: local.fridayOpenTime,
      friCloseTime: local.fridayCloseTime,
      isSatClosed: ChoiceBool(local.isSaturdayClosed).asYNNull,
      satOpenTime: local.saturdayOpenTime,
      satCloseTime: local.saturdayCloseTime,
    );
  }
}
